---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: draft-os
description: Personal bare bone image for my daily use

# Base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - from-file: recipe_modules/dnf.yml 
  - from-file: recipe_modules/flatpak.yml
  - from-file: recipe_modules/nvidia.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
